from gevent import monkey
monkey.patch_all()
import gevent

import requests, time, json
before = time.time()

def post(*args, **kwargs):
    r = requests.post(*args, **kwargs)
    print r.content

data = [
    {'gid': 1, 'nid': 2, 'aid':1 , 'pid':0 , 'jid':0 , 'masterjid':0 , 'epoch':1415524773 , 'appname':'jumpscale:portal' , 'level':1 , 'type':'UNKNOWN' , 'state':'NEW' , 'errormessage':'ImportError: cannot import name cloudbroker' , 'errormessagepub':'' , 'category':'', 'tags':'', 'code':'/opt/jumpscale/libext/cloudbrokerlib/baseactor.py', 'funcname':'<module>', 'funcfilename':'/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py', 'funclinenr': 1, 
    'backtrace': 'Traceback (most recent call last):\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py", line 309, in activateActor\n    result = self.ws.actorsloader.getActor(appname, actor)\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py", line 114, in getActor\n    aobj = loader.activate()\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py", line 213, in activate\n    args=args, makeCopy=True)()\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py", line 250, in generate\n    result = self._import(cg.getClassName(), cg.getClassName(), path)\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py", line 270, in _import\n    exec("import %s" % name)\n~   File "<string>", line 1, in <module>\n~   File "/opt/jumpscale/apps/portals/main/base/cloudapi__locations/methodclass/cloudapi_locations.py", line 3, in <module>\n    from cloudbrokerlib.baseactor import BaseActor\n~   File "/opt/jumpscale/libext/cloudbrokerlib/baseactor.py", line 1, in <module>\n    from . import cloudbroker\n~ ImportError: cannot import name cloudbroker\n', 
    'backtracedetailed':'  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py" Line 309, in activateActor\n    result = self.ws.actorsloader.getActor(appname, actor)\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py" Line 114, in getActor\n    aobj = loader.activate()\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py" Line 213, in activate\n    args=args, makeCopy=True)()\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py" Line 250, in generate\n    result = self._import(cg.getClassName(), cg.getClassName(), path)\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py" Line 270, in _import\n    exec("import %s" % name)\n  File "/opt/jumpscale/apps/portals/main/base/cloudapi__locations/methodclass/cloudapi_locations.py" Line 3, in <module>\n    from cloudbrokerlib.baseactor import BaseActor\n  File "/opt/jumpscale/libext/cloudbrokerlib/baseactor.py" Line 1, in <module>\n    from . import cloudbroker\n', 
    'extra':'', 'lasttime':1415628446, 'closetime': 0, 'occurrences': 13},
    {'gid': 2, 'nid': 3, 'aid':2 , 'pid':1 , 'jid':1 , 'masterjid':1 , 'epoch':1415524774 , 'appname':'jumpscale:portal' , 'level':1 , 'type':'UNKNOWN' , 'state':'NEW' , 'errormessage':'ImportError: cannot import name cloudbroker' , 'errormessagepub':'' , 'category':'', 'tags':'', 'code':'/opt/jumpscale/libext/cloudbrokerlib/baseactor.py', 'funcname':'<module>', 'funcfilename':'/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py', 'funclinenr': 1, 
    'backtrace': 'Traceback (most recent call last):\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py", line 309, in activateActor\n    result = self.ws.actorsloader.getActor(appname, actor)\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py", line 114, in getActor\n    aobj = loader.activate()\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py", line 213, in activate\n    args=args, makeCopy=True)()\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py", line 250, in generate\n    result = self._import(cg.getClassName(), cg.getClassName(), path)\n~   File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py", line 270, in _import\n    exec("import %s" % name)\n~   File "<string>", line 1, in <module>\n~   File "/opt/jumpscale/apps/portals/main/base/cloudapi__locations/methodclass/cloudapi_locations.py", line 3, in <module>\n    from cloudbrokerlib.baseactor import BaseActor\n~   File "/opt/jumpscale/libext/cloudbrokerlib/baseactor.py", line 1, in <module>\n    from . import cloudbroker\n~ ImportError: cannot import name cloudbroker\n', 
    'backtracedetailed':'  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portal/PortalRest.py" Line 309, in activateActor\n    result = self.ws.actorsloader.getActor(appname, actor)\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py" Line 114, in getActor\n    aobj = loader.activate()\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/portalloaders/ActorsLoader.py" Line 213, in activate\n    args=args, makeCopy=True)()\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py" Line 250, in generate\n    result = self._import(cg.getClassName(), cg.getClassName(), path)\n  File "/usr/local/lib/python2.7/dist-packages/JumpScale/portal/codegentools/CodeGenerator.py" Line 270, in _import\n    exec("import %s" % name)\n  File "/opt/jumpscale/apps/portals/main/base/cloudapi__locations/methodclass/cloudapi_locations.py" Line 3, in <module>\n    from cloudbrokerlib.baseactor import BaseActor\n  File "/opt/jumpscale/libext/cloudbrokerlib/baseactor.py" Line 1, in <module>\n    from . import cloudbroker\n', 
    'extra':'', 'lasttime':1415628447, 'closetime': 0, 'occurrences': 14},
]
    # {'name': 'katkoot', 'email': 'katkoot@codescalers.com', 'born': 'Wed, 05 Dec 2012 09:53:07 GMT'},

gevent.joinall([gevent.spawn(post, 'http://localhost:5000/system_eco', headers={'Content-Type': 'application/json'}, data=json.dumps(d)) for d in data])

print time.time() - before