#!/usr/bin/env python
from JumpScale import j
import argparse
j.application.start("jpackage")
from JumpScale.baselib import cmdutils

parser = argparse.ArgumentParser()
parser.add_argument('-m', '--message', required=False, help='Commit message to publish package')

packages, args = cmdutils.getJPackage(parser,installed=True)
for package in packages:
    package.publish(args.message,package.domain)

j.application.stop()
