#!/usr/bin/env python
from JumpScale import j
import argparse
j.application.start("jpackages")
from JumpScale.baselib import cmdutils

parser = argparse.ArgumentParser()
package, args = cmdutils.getJPackage(parser)

package.checkout()
j.application.stop()
