#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackage")
from JumpScale.baselib import cmdutils

package, args = cmdutils.getJPackage()
j.packages.publish(args.message, package.domain)
j.application.stop()
