#!/usr/bin/env python
from JumpScale import j

j.application.appname = "jpackage"
j.application.start()

import JumpScale.baselib.jpackages

j.packages.updateMetaData(force=True)

j.application.stop()
