#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackage")
import JumpScale.baselib.jpackages

print "upload package to blobstor"
package=j.packagesi.find()
if package<>None:
    package.upload()
else:
    raise RuntimeError("Could not find package.")

j.application.stop()
