#!python
import sys
sys.path.insert(0,"lib")

from JumpScale import j

j.application.appname = "jpackages"
j.application.start()

import JumpScale.baselib.jpackages

print "upload package to blobstor"

package=j.packagesi.find()
package.install(reinstall=True)


j.application.stop()
