#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackage")
from JumpScale.baselib import cmdutils
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-m','--message',required=False, help='Commit message')

package, args = cmdutils.getJPackage(parser)
j.packages.publish(args.message, package.domain)
j.application.stop()
