#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackage")
from JumpScale.baselib import cmdutils

print "download package to blobstor"
package, args = cmdutils.getJPackage()
package.download()
j.application.stop()
