#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackages")
from JumpScale.baselib import cmdutils

parser = cmdutils.ArgumentParser()
parser.add_argument('-r', '--reinstall', required=False, action='store_true', help='Reinstall found package')
parser.add_argument('-s', '--single', required=False, action='store_true', help='Do not install dependencies')
parser.add_argument('--debug', required=False, action='store_true', help='Sets debug_mode for package')
parser.add_argument('--nodownload', required=False, action='store_true', help='skips download')

packages, args = cmdutils.getJPackage(parser)
for package in packages:

    dependencies = not args.reinstall or not package.isInstalled()

    if args.single:
        dependencies=False
        
    if args.debug:
        package.setDebugMode()

    download=True
    if args.nodownload:
    	download=False

    package.install(dependencies=dependencies, reinstall=args.reinstall,download=download)

j.application.stop()
