#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackages")
import JumpScale.baselib.jpackages

print "upload package to blobstor"
package=j.packagesi.find()
package.install(reinstall=True)
j.application.stop()
