#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackages")
from JumpScale.baselib import cmdutils
import argparse

packages, args = cmdutils.getJPackage(parser,installed=True)
for package in packages:
    package.package(dependencies=args.all)

j.application.stop()
