#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackages")
from JumpScale.baselib import cmdutils

package, args = cmdutils.getJPackage()
package.setDebugMode()
j.application.stop()
