#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackages")


packages=j.packages.find(domain="*",name="*")
for package in packages:

    package.download(allplatforms=True)

j.application.stop()
