#!/usr/bin/env python
from JumpScale import j
import argparse
j.application.start("jpackages")
from JumpScale.baselib import cmdutils

parser = argparse.ArgumentParser()
parser.add_argument('-a', '--all', required=False, action='store_true', help='do also for dependencies (all jpackages)')
package, args = cmdutils.getJPackage(parser)

package.codeExport(dependencies=args.all)
j.application.stop()
