#!/usr/bin/env python
from JumpScale import j
j.application.start("jpackage")
from JumpScale.baselib import cmdutils

print "upload package to blobstor"
package, args = cmdutils.getJPackage()
package.upload()
j.application.stop()
