#!/usr/bin/env python
from JumpScale import j
j.application.start("jspush")
import JumpScale.baselib.mercurial

def getRepos():
    result=[]
    accounts=j.system.fs.listDirsInDir("/opt/code", recursive=False, dirNameOnly=True, findDirectorySymlinks=True)
    accounts=j.console.askChoiceMultiple(accounts,"select bitbucketaccounts")
    for account in accounts:
        accountdir="/opt/code/%s"%account
        if j.system.fs.exists():
            bitbucket=j.clients.bitbucket.getBitbucketConnection(accountdir)
            for reponame in j.system.fs.listDirsInDir(accountdir,recursive=False, dirNameOnly=True, findDirectorySymlinks=True):
                repodir="%s/%s"%(accountdir,reponame)
                cl=bitbucket.getMercurialClient(repodir)
                # cl=j.clients.mercurial.getClient(item)
                result.append((account,reponame,cl))


for account,reponame,client in getRepos()
    from IPython import embed
    print "DEBUG NOW commit"
    embed()
    #cl.commit()

j.application.stop()
