#!/usr/bin/env python
from JumpScale import j

j.application.appname = "jsupdate"
j.application.start()


import JumpScale.baselib.mercurial
j.application.shellconfig.interactive=True

for item in j.system.fs.listDirsInDir("/opt/code/jumpscale"):
    print "update/merge/commit/push for %s"%item
    cl=j.clients.mercurial.getClient(item)
    cl.updatemerge()

