#!/usr/bin/env python
from JumpScale import j
j.application.start("jscommit")
import JumpScale.baselib.mercurial


for item in j.system.fs.listDirsInDir("/opt/code/jumpscale"):
    print "update/merge/commit/push for %s"%item
    cl=j.clients.mercurial.getClient(item)
    cl.commit()

j.application.stop()
