#!/usr/bin/env python
from JumpScale import j
j.application.start("jsupdate")
import JumpScale.baselib.mercurial

for subdir in ["jumpscale","incubaid","dfsio_blobstore"]:
    if j.system.fs.exists("/opt/code/%s"%subdir):
        
        for item in j.system.fs.listDirsInDir("/opt/code/%s"%subdir):
            print "update/merge/commit/push for %s"%item
            cl=j.clients.mercurial.getClient(item)
            cl.updatemerge()

j.application.stop()
