#!/usr/bin/env python
from JumpScale import j
from JumpScale.baselib import cmdutils

j.application.start("jsprocess_disable")

opt = cmdutils.getProcess()

j.tools.startupmanager.enableProcess(opt.domain, opt.name)

j.application.stop()
