#!/usr/bin/env python
from JumpScale import j
from JumpScale.baselib import cmdutils

j.application.start("jsprocess_monitor")

raise RuntimeError("to implement")

# j.tools.startupmanager.startProcess(opt.domain, opt.name)

j.application.stop()
